### ISSUE TITLE
Feature Request: Enter/Exit Animations

### ISSUE THREAD

**Issue by Newbie012** [chakra-ui/ark#1117]
### Description

I've been looking at [Dialog](https://ark-ui.com/docs/react/components/dialog), [Popover](https://ark-ui.com/docs/react/components/popover), (and possibly a [Drawer?](https://github.com/chakra-ui/ark/blob/main/website/src/theme/recipes/drawer.ts)) components, and I believe adding enter/exit animations could be beneficial.

### Proposed Solution or API

```css
@keyframes fadeIn {
  from {
    opacity: 0;
  }
  to {
    opacity: 1;
  }
}

@keyframes fadeOut {
  from {
    opacity: 1;
  }
  to {
    opacity: 0;
  }
}

.DialogOverlay[data-state='open'],
.DialogContent[data-state='open'] {
  animation: fadeIn 300ms ease-out;
}

.DialogOverlay[data-state='closed'],
.DialogContent[data-state='closed'] {
  animation: fadeOut 300ms ease-in;
}
```
copied from [radix-ui docs](https://www.radix-ui.com/docs/primitives/guides/animation)
