### ISSUE TITLE
Dialog freezes when closed on an inactive Chrome tab

### ISSUE THREAD

**Issue by giero** [chakra-ui/ark#3002]
### Description

When I delay closing the Dialog and switch to another browser tab in Chrome, and then return to the tab with Dialog, it is still open and any interaction is blocked.

### Link to Reproduction (or Detailed Explanation)

https://codesandbox.io/p/sandbox/ark-ui-dialog-forked-s7wfhn

### Steps to Reproduce

1. Go to [sandbox](https://codesandbox.io/p/sandbox/ark-ui-dialog-forked-s7wfhn) in Chrome
2. Click on **Open Dialog**
3. Click on **Delayed close** and switch fast to another browser tab for 2-3 seconds (closing has 1s cooldown)
4. Switch back to tab with sandbox - Dialog is still open and is blocking UI (only refreshing the page works)

### Ark UI Version

4.1.2

### Framework

- [X] React
- [ ] Solid
- [ ] Vue

### Browser

Google Chrome

### Additional Information

I've done some tests and I'm almost certain that the problem lies when Dialog is animating.

When I removed
```css
[data-scope="dialog"][data-part="content"][data-state="open"] {
  animation: scaleIn 0.25s ease-out;
}

[data-scope="dialog"][data-part="content"][data-state="closed"] {
  animation: scaleOut 0.2s ease-in;
}
```
from css - Dialog closes, but backdrop is frozen.
Removing all animation code from css makes the Dialog close properly.
