### ISSUE TITLE
Missing `--index` CSS var in solid-js Toast

### ISSUE THREAD

**Issue by jakst** [chakra-ui/ark#3405]
### Description

The `--index` CSS var is not present in the solid version of Ark making it impossible to create the staggered overlap effect that you have for toasts in your docs example without major workarounds. I checked the React version, and it's there.

Currently I use this CSS to get around the issue
```css
[data-scope="toast"][data-part="root"] {
  &:nth-child(1) {
    --index: 0;
  }

  &:nth-child(2) {
    --index: 1;
  }

  &:nth-child(3) {
    --index: 2;
  }

  &:nth-child(4) {
    --index: 3;
  }

  /* ... and continues for as many toasts as I want to support */
}
```

See the linked reproduction where I have added the CSS for the workaround.

Also, separate issue, but if you look at `src/routes/index.tsx` you'll see `<Toaster toaster={toaster} style={{ '--first-height': '' }}>`. I had to empty `--first-height`, because the default value make the rows like 16px tall. Remove that piece of styling to see that issue.

### Link to Reproduction (or Detailed Explanation)

https://stackblitz.com/edit/github-1hgkbbln-zgd3h26e?file=src%2Ftoast.css

### Steps to Reproduce

1. Open a couple of toasts and see the staggered effect working
2. Go to `./src/toast.css` and comment out all the `nth-child` styles (rows 41-119)
3. Reload the app and open a few toasts again
4. Notice that all toasts overlay each other fully

### Ark UI Version

5.1.0

### Framework

- [ ] React
- [x] Solid
- [ ] Vue

### Browser

Chrome

### Additional Information

I took the styling from here https://github.com/chakra-ui/zag/blob/main/shared/src/css/toast.css. I figured it was some sort of officially working version.
